export * as blockEditor from '@wordpress/block-editor'
export * as blocks from '@wordpress/blocks'
export * as components from '@wordpress/components'
export * as compose from '@wordpress/compose'
export * as data from '@wordpress/data'
export * as element from '@wordpress/element'
export * as hooks from '@wordpress/hooks'
export * as __ from '@wordpress/i18n'
export { default as serverSideRender } from '@wordpress/server-side-render'
